[package]
name = "jwt"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>", "Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Create and parse JWT in a strongly typed way."
homepage = "https://github.com/lawliet89/rust-jwt"
repository = "https://github.com/lawliet89/rust-jwt"
keywords = ["jwt", "web", "api", "token", "json"]

[dependencies]
ring = { version = "0.7", features = ["rsa_signing"] }
rustc-serialize = "0.3"
untrusted = "0.3"
