[package]
name = "biscuit"
version = "0.0.2"
authors = ["Yong Wen Chua <me@yongwen.xyz>", "Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "A library to work with JSON Web Tokens (JWT)."
homepage = "https://github.com/lawliet89/biscuit"
repository = "https://github.com/lawliet89/biscuit"
documentation = "https://docs.rs/biscuit/"
keywords = ["jwt", "web", "token", "json"]
categories = ["authentication", "web-programming"]

[badges]
travis-ci = { repository = "lawliet89/biscuit" }

[lib]
name = "biscuit"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[dependencies]
chrono = "0.3"
data-encoding = "1.2.0"
lazy_static = "0.2"
num = "0.1.37"
ring = { version = "0.7.5", features = ["rsa_signing"] }
serde = "0.9"
serde_derive = "0.9"
serde_json = { version = "0.9", features = ["preserve_order"] }
untrusted = "0.3"
url = "^1.0"

[dev-dependencies]
serde_test = "0.9"
